/*
 * Copyright 2009-2011, Andrea Anzani. All rights reserved.
 * Distributed under the terms of the MIT License.
 */
#ifndef _NOTIFY_MESSAGE_H
#define _NOTIFY_MESSAGE_H

enum {
	STR_CONTACT_NAME,
	STR_PERSONAL_STATUS,
	STR_ROOM_NAME,
	STR_ROOM_SUBJECT,

	PTR_AVATAR_BITMAP,
	PTR_ROOM_BITMAP,

	INT_ACCOUNT_STATUS,
	INT_CONTACT_STATUS,
	INT_USER_PERMS,
	INT_ROOM_MEMBERS,
	INT_NEW_MESSAGE,
	INT_NEW_MENTION,

	INT_CONV_VIEW_SELECTED,
	INT_ACCOUNTS_UPDATED
};

#endif	// _NOTIFY_MESSAGE_H
