#ifndef _IRC_CONSTANTS_H
#define _IRC_CONSTANTS_H

enum UserRole {
	ROOM_MEMBER				= 0,
	ROOM_HALFOP				= 1,
	ROOM_OPERATOR			= 2,
	IRC_OPERATOR			= 3
};


#define RPL_WELCOME 1
#define RPL_WHOISUSER 311
#define RPL_ENDOFWHO 315
#define RPL_ENDOFWHOIS 318
#define RPL_TOPIC 332
#define RPL_WHOREPLY 352
#define RPL_NAMREPLY 353
#define RPL_MOTD 372
#define RPL_MOTDSTART 375
#define RPL_ENDOFMOTD 376

#define ERR_NONICKNAMEGIVEN 431
#define ERR_ERRONEUSNICKNAME 432
#define ERR_NICKNAMEINUSE 433

#endif // _IRC_CONSTANTS_H
