.DEFAULT_GOAL := default

libinterface:
	$(MAKE) -f libs/libinterface/Makefile

librunview:
	$(MAKE) -f libs/librunview/Makefile

libsupport:
	$(MAKE) -f libs/libsupport/Makefile

all: libinterface librunview libsupport

default: all
