all:
	gcc BeTick.cpp -c -o BeTick.o
	gcc TickApp.cpp -c -o TickApp.o
	gcc TickCore.cpp -c -o TickCore.o
	gcc TickView.cpp -c -o TickView.o
	gcc TickWindow.cpp -c -o TickWindow.o
	gcc BeTick.o TickApp.o TickCore.o TickView.o TickWindow.o -o BeTick -lgame -lbe
